config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :works, except: [:show] do
    put :sort, on: :collection
  end

  #custom scope
  get 'angular', to: 'works#angular'
  get 'work/:id', to: 'works#show', as: 'work_show'

  get 'contact', to: 'pages#contact'
  get 'about-me', to: 'pages#about'
  get 'tech_news', to: 'pages#tech_news'

  resources :topics, only: [:index, :show]


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/work.rb
class Work < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, WorkUploader
  mount_uploader :main_image, WorkUploader

  # Custom scopes
  def self.ruby_on_rails_items
    where(subtitle: "Ruby on Rails")
  end

  # Custom scopes
  def self.angular
    where(subtitle: "Angular")
  end

  def self.by_position
    order('position ASC')
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  layout "work"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :edit, :update, :sort]}, site_admin: :all

  def index
    @works = Work.by_position
  end

  def sort
    params[:order].each do |k, v|
      Work.find(v[:id]).update(position: v[:position])
    end
    render nothing: true
  end

  def angular
    @angular_work = Work.angular
  end

  def show
    @page_title = @work.title
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to works_path, notice: "Portfolio was successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @work.update(work_params)
      redirect_to works_path, notice: "Portfolio was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @work.destroy
    redirect_to works_path, notice: "Portfolio was successfully deleted"
  end




  private


  def work_params
    params.require(:work).permit(:title,
                                 :subtitle,
                                 :body,
                                 :main_image,
                                 :thumb_image,
                                 technologies_attributes: [:id, :name, :_destroy])
  end

  def set_work
    @work = Work.find(params[:id])
  end
end

app/helpers/works_helper.rb
module WorksHelper

end

app/views/works/_form.html.erb
<%= form_for(work) do |f| %>
  <% if work.errors.any? %>
    <% work.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>

<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label class="btn btn-outline-info">
        Upload thumb image<%= f.file_field :thumb_image, style: 'display:none;' %>

      </label>

    </div>

    <div class="form-group">
      <label class="btn btn-outline-info">
        Upload main image<%= f.file_field :main_image, style: 'display:none;' %>
      </label>
    </div>

  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', rows: 15 %>
    </div>
  </div>
  <div class="col-md-12">
    <hr>
    <div>
      <h4>Technologies used:</h4>
        <%= f.fields_for :technologies do |tech| %>
          <%= render 'technology_fields', f: tech %>
        <% end %>
      <div>
        <%= link_to_add_association 'Add Technology', f, :technologies %>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
<% end %>

  </div>
</div>

app/views/works/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove item', f %>
</div>

app/views/works/_work.html.erb
<div class="col-lg-4 col-md-6 col-sm-12">
  <div class="card mb-4 box-shadow" data-id="<%= work.id %>">
    <a href="<%= work_show_path(work) %>">
      <%= image_tag work.thumb_image.url, width: '100%', class: "card-img-top" if work.thumb_image.url %>
      </a>
    <div class="card-body">
      <p class="card-title"><%= work.title %></p>
      <p class="card-text"><%= work.subtitle %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to work.title, work_show_path(work), class: 'btn btn-sm btn-outline-secondary' %>
          <%= link_to 'Edit', edit_work_path(work), class: 'btn btn-sm btn-outline-secondary' if logged_in?(:site_admin) %>
          <%= link_to 'Delete', work, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-sm btn-outline-secondary' if logged_in?(:site_admin) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/works/angular.html.erb
// Custom scopes for work items

<h1>Portfolio Items</h1>

<p id="notice"><%= notice %></p>

<%= link_to 'Create a new Portfolio', new_work_path %>

<% @angular_work.each do |work| %>
  <h2> <%= link_to work.title, work_show_path(work) %> </h2>
  <h4> <%= work.subtitle %> </h4>
  <p> <%= work.body %> </p>
  <%= image_tag work.thumb_image unless work.thumb_image.blank? %>
  <br>
  <%= link_to 'Edit', edit_work_path(work) %>
  <%= link_to 'Delete', work, data: { confirm: 'Are you sure?' }, method: :delete %>
<% end %>

app/views/works/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio</h1>

  <%= render 'form', work: @work %>
</div>

app/views/works/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row  <%= "sortable" if logged_in?(:site_admin) %>">

      <%= render @works %>

    </div>
  </div>
</div>

app/views/works/new.html.erb
<div class="container">
  <div class="portfolio-form">
    <h1>Create a new portfolio item</h1>

    <%= render 'form', work: @work %>

  </div>
</div>

app/views/works/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @work.main_image.url if @work.main_image.url %>
      <br>
    </div>
    <div class="col-md-5">
     <h4>
       <%= @work.title %>
     </h4>
      <p>
        <%= @work.body %>
      </p>
      <hr>
      <h5>Technologies used:</h5>
        <% @work.technologies.each do |t| %>
        <p>
          <%= t.name %>
        </p>
        <% end %>
      <%= link_to 'Edit', edit_work_path(@work), class: 'btn btn-outline-secondary btn-sm' if logged_in?(:site_admin) %>
    </div>
  </div>
</div>