config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :works, except: [:show] do
    put :sort, on: :collection
  end

  #custom scope
  get 'angular', to: 'works#angular'
  get 'work/:id', to: 'works#show', as: 'work_show'

  get 'contact', to: 'pages#contact'
  get 'about-me', to: 'pages#about'
  get 'tech_news', to: 'pages#tech_news'

  resources :topics, only: [:index, :show]


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light app-nav">
  <a class="navbar-brand" href="/">Sergio Alves</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= nav_helper('nav-link', 'span') %>
      <%= login_helper("nav-link") %>
    </div>
  </div>
</nav>

app/views/shared/_blog_actions.html.erb
<% if logged_in?(:site_admin) %>
  <%= icon_status_helper(blog) %>
  <%= icon_edit_helper(blog) %>
  <%= icon_trash_helper(blog) %>
<% end %>

app/views/shared/_blog_breadcrump.html.erb
<nav aria-label="breadcrumb">
  <%= link_to blog.topic.title, topic_path(blog.topic), class: "breadcrumb-item" %>
  <span class="breadcrumb-item active">Published: <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</span>
  <span class="pull-right blogcrumb">
    <%= render 'shared/blog_actions', blog: blog %>
  </span>
</nav>
<br>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h3 class="blog-title">Sergio Alves Blog</h3>
    <p class="lead blog-description">A Blog to share knowledge and experiences</p>
    <%= link_to 'Write a new Blog', new_blog_path, class: 'btn btn-outline-success btn-sm' if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navblog">
  <div class="container">
    <%= link_to 'Sergio Alves', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= nav_helper('nav-link', 'span') %>
        <%= login_helper('nav-link') %>
      </div>
    </div>

  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>Topics</h4>
      <div class="topics-sidebar">
        <%= topic_generator %>
        <%= link_to 'All Topics', topics_path %>

      </div>
  </div>
  <div class="sidebar-module">
    <h4>Find me here:</h4>
    <ol class="list-unstyled social-links">
      <%= render 'shared/social_links' %>
    </ol>
  </div>
</div>
</div>

app/views/shared/_social_links.html.erb
<li><a href="https://github.com/salvescoding" target="_blank"><%= fa_icon 'github-alt' %></li></a>
<li><a href="https://www.linkedin.com/in/sergio-alves-415a8679/" target="_blank"> <%= fa_icon 'linkedin' %></li></a>
<li><a href="https://www.instagram.com/sergioalves23/?hl=es" target="_blank"> <%= fa_icon 'instagram' %></li></a>

app/views/shared/_work_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <div class="float-right">

        <%= link_to 'View all portfolio items',  works_path, class: "btn btn-sm btn-outline-secondary" %>

        <a href="#" class="btn btn-sm btn-outline-secondary">Back to top</a>

    </div>
    <p class="copyright-work"><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_work_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <!-- <h4 class="text-white">About</h4>
        <p class="text-muted">Since a very young age, I have always been very creative and extremely curious.
          After discovering my passion for web development and my interest in the tech world I couldn't get enough. I started to create small websites for friends and family.
          Meanwhile, I also created my first full stack web app in only two weeks.

        In a world of continuous learning, the is no room for boredness.</p> -->
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Options</h4>
        <ul class="list-unstyled">
          <%= nav_helper('text-white', 'li') %>
          <li><%= login_helper('text-white') %></li>
          <li><%= link_to 'Create a new Portfolio', new_work_path, class: 'text-white' if logged_in?(:site_admin)%></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="/" class="navbar-brand d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
      <strong>Sergio Alves</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>